name: Rosalie Prom
bio: Coder, creative & innovator.
description: Rosie's website.
external-image: true
picture: 'https://pbs.twimg.com/profile_images/928246958128377856/WnbU7Zyj_400x400.jpg'
resume: true
resume-external: true
resume-url: >-
  https://drive.google.com/file/d/11xVdWogFHwxP7VT3qFctHjTf8njcrz8y/view?usp=sharing
url: 'http://developerpeachy.github.io'
permalink: '/:title/'
twitter: developerpeachy
instagram: developerpeachy
linkedin: rosalinda-prom-15508a85
spotify: rosalieprom
github: developerpeachy
email: rosalinda.prom@gmail.com
authors:
  rosalieprom:
    name: developerpeachy
    bio: 'Coder, creative & innovator.'
    external-image: 'true'
    picture: >-
      https://pbs.twimg.com/profile_images/928246958128377856/WnbU7Zyj_400x400.jpg
    twitter: developerpeachy
width: normal
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins_dir:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
jekyll-mentions:
  base_url: 'https://github.com'
