# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Developer Peachy
email: rosalinda.prom@gmail.com
description:
  "<h3>Welcome to my GitHub page!</h3><h1>Peachy's Journal</h1> <h3>Awesome blog for experimental purposes!</h3>Will be posting some articles soon :-)"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developerpeachy.github.io" # the base hostname & protocol for your site
twitter_username: developerpeachy
github_username:  Peaches2

# Build settings
markdown: kramdown
